# Generated by Django 4.0.1 on 2023-06-01 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kasir', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasien', '0002_initial'),
        ('antrian', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLayananRadiologi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananRadiologi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=250, null=True)),
                ('harga', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologi.kategorilayananradiologi')),
            ],
        ),
        migrations.CreateModel(
            name='LayananRadiologiPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_layanan', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DILAYANI', 'Dilayani'), ('BATAL', 'Batal')], default='MENUNGGU', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosa', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('antrian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.antrian')),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologi_dokter', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.invoice')),
                ('layanan_radiologi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologi.layananradiologi')),
                ('pasien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.pasien')),
                ('pendaftaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasien.pendaftaran')),
                ('petugas_radiologi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologi_petugas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='radiologi/')),
                ('layanan_radiologi_pasien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologi.layananradiologipasien')),
            ],
        ),
    ]
